---
- name: Set up infrastructure-related parameters
  template:
    src: '{{ playbook_dir }}/templates/parameters.yml.dist'
    dest: '{{ ansistrano_release_path.stdout }}/app/config/parameters.yml'

- name: Instal Composer dependencies
  composer:
    command: install
    working_dir: '{{ ansistrano_release_path.stdout }}'

- name: Create DB in not exists
  command: '{{ release_console_path }} doctrine:database:create --if-not-exists --env=prod'
  register: create_db_output
  changed_when: create_db_output.stdout is not search('already exists. Skipped')

- name: Execute migrations
  command: '{{ release_console_path }} doctrine:migrations:migrate --no-interaction'
  register: db_migrations_result
  changed_when: db_migrations_result.stdout is not search('No migrations to execute')

- name: Clear the cache
  command: '{{ release_console_path }} cache:clear --no-warmup --env=prod'

- name: Warm up the cache
  command: '{{ release_console_path }} cache:warmup --env=prod'

- name: Install bundle assets
  command: '{{ release_console_path }} assets:install {{ release_web_path }} --symlink --no-debug --env=prod'

- name: Install node dependencies
  command: yarn install
  args:
    chdir: '{{ ansistrano_release_path.stdout }}'

- name: Install Webpack Encore assets
  command: './node_modules/.bin/encore production'
  args:
    chdir: '{{ ansistrano_release_path.stdout }}'

- name: Setup directory permissions for var/
  file:
    path: "{{ release_var_path }}"
    state: directory
    mode: 0777
    recurse: true

