---
- hosts: vb

  vars_files:
    - ./vars/deploy_vault.yml
    - ./vars/vars.yml
    - ./vars/deploy_vars.yml

  vars:
    ansible_python_interpreter: /usr/bin/python3

    release_console_path: "{{ ansistrano_release_path.stdout }}/bin/console"
    release_var_path: "{{ ansistrano_release_path.stdout }}/var"
    release_web_path: "{{ ansistrano_release_path.stdout }}/web"
    release_logs_path: "{{ ansistrano_release_path.stdout }}/var/logs"

    ansistrano_deploy_to: "{{ project_deploy_dir }}"
    ansistrano_deploy_via: git
#    ansistrano_git_repo: "https://github.com/sserge2000/ansistrano-test.git"
    ansistrano_git_repo: "https://github.com/sserge2000/ansistrano_test2.git"
    ansistrano_git_branch: master
    ansistrano_keep_releases: 3

    ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/deploy/after-symlink-shared.yml"

    # Arrays of directories and files to be shared.
    # The following arrays of directories and files will be symlinked to the current release directory after the 'update-code' step and its callbacks
    # Notes:
    # * Paths are relative to the /shared directory (no starting /)
    # * If your items are in a subdirectory, write the entire path to each shared directory
    #
    # Example:
    # ansistrano_shared_paths:
    #   - path/to/first-dir
    #   - path/next-dir
    # ansistrano_shared_files:
    #   - my-file.txt
    #   - path/to/file.txt
    ansistrano_shared_paths:
      - var/logs
      - node_modules

  roles:
    - ansistrano.deploy

  environment:
    SYMFONY_ENV: prod
