---
- hosts: vb

  vars_files:
    - ./vars/vars.yml

  vars:
    ansible_python_interpreter: /usr/bin/python3

    ansistrano_deploy_to: "{{ project_deploy_dir }}"
    ansistrano_rollback_before_symlink_tasks_file: "{{ playbook_dir }}/rollback/before-symlink.yml"

  roles:
    - ansistrano.rollback
